# Generated by Django 4.1.2 on 2023-01-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_posts_group_id_remove_group_postid_group_postid'),
    ]

    operations = [
        migrations.AddField(
            model_name='joingroup',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='postId',
            field=models.ManyToManyField(blank=True, to='myapp.posts'),
        ),
    ]
