# Generated by Django 4.0.1 on 2023-01-29 16:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_group_postid_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='th.jpeg', max_length=255, null=True, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='avatar.svg', max_length=255, null=True, verbose_name='images'),
        ),
    ]
